### ISSUE TITLE
Developing app in Flutter

### ISSUE THREAD

**Issue by PatilShreyas** [scorelab/dengue-stop#118]
Flutter is a new framework by Google to develop cross platform applications. If this app is developed using Flutter we can generate Android, iOS, Web, Windows, Mac, Linux executable applications which can run on different platforms. LMK if this looks good to you.

Reference - [GSoC 2020](https://www.scorelab.org/gsoc-2020/#denguestop02)

**Comment by dilum1995** [comment]
I would love to work on this project if we are moving ahead with Flutter.

**Comment by SahanDisa** [comment]
#120 demo version for flutter app

**Comment by tanvidhope** [comment]
Hey @PatilShreyas I am interested in this, can you let me know what to do?

**Comment by SahanDisa** [comment]
#128 fully functional flutter app with user authentication
